### ISSUE TITLE
AcceptanceMark Command Line Tool

### ISSUE THREAD

**Issue by bizz84** [bizz84/AcceptanceMark#1]
## Purpose: Write a command line tool to generate XCTests from a set of `.md` files encoding business rules.

See [amtool Specification file](https://github.com/bizz84/AcceptanceMark/blob/master/amtool-spec.md) for details.
### TODO
- [x] Add **Xcode macOS Command Line Tool** target to project, named `amtool`
- [ ] Parse `--input-dir` and `-i` command line argument to specify input directory for reading `.md` files
- [ ] For each `.md` file in input directory, run test generator component
